import torch
import random
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()


prompts = [
    "High-resolution DSLR photo of a single whole with white background, unsliced apple with smooth. The apple is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, making the apple in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced apricot with smooth, orange skin. The apricot is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the apricot in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced avocado with smooth green skin. The avocado is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the avocado in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced banana with vibrant yellow skin. The banana is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the banana in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced blackberry with deep purple-black color and textured surface. The blackberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the blackberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced blueberry with smooth, blue skin. The blueberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the blueberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cantaloupe with rough, netted skin. The cantaloupe is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cantaloupe in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cherry with smooth, red skin. The cherry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cherry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced coconut with rough, brown husk. The coconut is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the coconut in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cranberry with smooth, red skin. The cranberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cranberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced date with smooth, brown skin. The date is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the date in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced dragonfruit with vibrant pink skin and green scales. The dragonfruit is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the dragonfruit in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced durian with spiky, greenish-brown skin. The durian is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the durian in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced fig with smooth, purple skin. The fig is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the fig in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced grape with smooth, green skin. The grape is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the grape in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced guava with smooth, green skin. The guava is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the guava in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced honeydew melon with smooth, pale yellow skin. The honeydew is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the honeydew in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced kiwi with fuzzy, brown skin. The kiwi is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the kiwi in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lemon with smooth, yellow skin. The lemon is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lemon in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lime with smooth, green skin. The lime is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lime in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lychee with rough, pink-red skin. The lychee is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lychee in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced mango with smooth, red-yellow skin. The mango is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the mango in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced nectarine with smooth, red-yellow skin. The nectarine is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the nectarine in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced orange with smooth, orange skin. The orange is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the orange in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced papaya with smooth, yellow-green skin. The papaya is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the papaya in sharp focus and the background slightly blurred."
    "High-resolution DSLR photo of a single whole with white background, unsliced passionfruit with smooth, purple skin. The passionfruit is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the passionfruit in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pear with smooth, green-yellow skin. The pear is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pear in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced persimmon with smooth, orange skin. The persimmon is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the persimmon in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pineapple with rough, spiky, green-brown skin. The pineapple is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pineapple in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced plum with smooth, purple-red skin. The plum is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the plum in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pomegranate with smooth, red skin. The pomegranate is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pomegranate in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced raspberry with vibrant red color and textured surface. The raspberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the raspberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced strawberry with vibrant red skin and green leaves. The strawberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the strawberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced ugli fruit with rough, yellow-green skin. The ugli fruit is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the ugli fruit in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced watermelon with smooth, green-striped skin. The watermelon is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the watermelon in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced carrot with smooth, orange skin. The carrot is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the carrot in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced broccoli with dark green florets. The broccoli is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the broccoli in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cauliflower with white, bumpy florets. The cauliflower is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cauliflower in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced bell pepper with smooth, vibrant red skin. The bell pepper is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the bell pepper in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pumpkin with rough, orange skin. The pumpkin is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pumpkin in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cucumber with smooth, green skin. The cucumber is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cucumber in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced tomato with smooth, red skin. The tomato is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the tomato in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced eggplant with smooth, deep purple skin. The eggplant is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the eggplant in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced zucchini with smooth, green skin. The zucchini is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the zucchini in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced potato with rough, brown skin. The potato is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the potato in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced onion with smooth, golden brown skin. The onion is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the onion in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced garlic with papery white skin. The garlic is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the garlic in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lettuce with vibrant green leaves. The lettuce is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lettuce in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced corn on the cob with golden yellow kernels. The corn is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the corn in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced beetroot with deep red-purple skin. The beetroot is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the beetroot in sharp focus and the background slightly blurred."
]




negative_prompt = "shadow, shiny, water, drops, sliced, cut, peeled, half, piece, ugly, tiling, out of frame, poorly drawn face, extra limbs, disfigured, deformed, body out of frame, blurry, bad anatomy, blurred, artifacts, bad proportions."


def get_fruit_name(prompt):
    fruit_name = prompt.split("unsliced ")[1].split(" with")[0]
    return fruit_name

for prompt_index, prompt in enumerate(prompts):
    for image_index in range(200):
        seed = random.randint(0, 2147483647)  
        generator = torch.manual_seed(seed)
        image = pipe(prompt,negative_prompt=negative_prompt,num_inference_steps=28,guidance_scale=5,generator=generator).images[0]
        image.save(f"./fruit_images/{get_fruit_name(prompts[prompt_index])}_{image_index + 1}.jpg")